### ISSUE TITLE
Cable issue

### ISSUE THREAD

**Issue by mor1mi** [AndreEbel/PyLinkam#3]
Hi AndreEbel
Thank you very much for making Pylinkam.   
I am Yuma.  I want to control linkam from python as well and I think Pylinkam is exactly what I need.  
This is first time for me to use Github, so maybe my manner is not good..If I am doing wrong, please let me know.  
My linkam is TMS94.  I believe this is same with you.  
I connected linkam with PC by USB to DB9 Female Serial Adapter (Crossover).  
Then I tried the example you made....It give me error....
I am not sure if we have connection with linkam..  Do you have any idea to fix this or check something?
I am sorry to ask you such a personal issue.  
<img width="491" alt="img" src="https://user-images.githubusercontent.com/86752937/129110695-99b92ef3-2d1e-4f5b-bf1b-a72d5b5c9756.PNG">

**Comment by AndreEbel** [comment]
Hi, I am glad this code can be useful to someone. 
This looks like a usb issue. 
Are you sure you have installed the pilot going with the usb to db9 cable ?

**Comment by mor1mi** [comment]
Thank you very much for your reply!  I am not sure what you mean by "pilot".  Do you mean device driver?

**Comment by AndreEbel** [comment]
Sorry yes i meant the driver indeed.

What is more, you need to make sure that the 9 pin serial port of your serial adapter is wired correctly to match the wiring of the TMS94. For this matter, see page 3 of the documentation in the 'doc' folder of the repo. 

If i remember well, i had to make a custom male to female db9 adpator to make it work.

**Comment by mor1mi** [comment]
Hi AndreEbel, 
Thank you very much for your reply.  
I got new cables today, and they work well!  
I put the info. of product for someone who has the same issues.  
Products from StarTech.com
>1Port USB to Serial RS232 Adapter Cable with COM Retention
>10ft DB9 RS232 Serial Null Modem Cable F/F

**Comment by AndreEbel** [comment]
Thanks for the reference of the cable ! 
I did not know this kind of cable existed. 
I updated the ReadMe accordingly so that people can get the right cable.

**Comment by AndreEbel** [comment]
In my opinion this issue is closed now. 
Please give details if you want to reopen it.
