### ISSUE TITLE
TMS94.temperature return wrong value and show error

### ISSUE THREAD

**Issue by mor1mi** [AndreEbel/PyLinkam#4]
I encountered the issue with "TMS94.temperature".  
For my purpose, I needed to record temp. so that I made code like...
```python
import PyLinkam as PL
import time
TMS94 = PL.programmer('COM13')
while True:
    T_C=TMS94.temperature
    print (T_C)
    time.sleep(1) #even if sleep(5)
```
TMS94.temperature sometimes return 0 or near 0 (like 0.3).  
Then right after this, I got an error of 
"invalid literal for int() with base 16:'\x80\x80\x800'" in decode_temperature (self).  

Do you know why or a better way to track the temperature in ramping(I need returned number)?

**Comment by AndreEbel** [comment]
I will look into it. 

If you use it once, like in the example notebook, does it return the right value ?

**Comment by AndreEbel** [comment]
I updated code and example to add a datalog function that save time, temperature, status and error in a csv file (#1). 
See the example notebook for more details.  
Close the issue if this solves your problem.

**Comment by mor1mi** [comment]
Thank you very much for your supports.  
Yes, it returns the right value if I use it once.  
But it sometimes returns the wrong value if I use it in a loop with an interval of 1 second.  
So it may be related to the response speed...So maybe the response of my linkam is slow.

**Comment by AndreEbel** [comment]
As you have closed the issue, i guess the solution I provided was working for you. 
Does the datalog function work properly for you ?

**Comment by mor1mi** [comment]
Thank you! I think it was because I requested the response every 0.1 sec for my purpose.  It works if I requested every 1 sec like you.  
Could you please try if the 0.1 sec works when you have time?

**Comment by AndreEbel** [comment]
Interesting ! I will try next time
